# .github/workflows/ci.yml

name: Go CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-check:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from GitHub
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Go
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22

      # Verify Go code formatting
      - name: Check code formatting
        run: go fmt ./...

      # Run go vet to find potential issues
      - name: Run go vet
        run: go vet ./...

      # 🔒 Skip tests for now
      # - name: Run tests
      #   run: go test ./...

      # ✅ Optional: Build Docker image (only runs if needed)
      - name: Build Docker image (optional)
        if: false # Set to true later
        run: docker build -t go-crud-api .

      # 🚀 Optional CD to Railway (disabled for now)
      - name: Deploy to Railway (future)
        if: false
        run: echo "CD step is disabled until network access is available."
